### ISSUE TITLE
quiz_02 폴더가 생기지 않습니다

### ISSUE THREAD

**Issue by Lee-Jong-Cheol** [encore-playdata/qna#10]
<img width="455" alt="캡처" src="https://user-images.githubusercontent.com/62085495/76810891-fff32600-6832-11ea-8c64-c70d0ea27e29.PNG">
<img width="458" alt="캡처1" src="https://user-images.githubusercontent.com/62085495/76810899-06819d80-6833-11ea-9ea2-b3f927140f6f.PNG">
<img width="464" alt="캡처2" src="https://user-images.githubusercontent.com/62085495/76810900-08e3f780-6833-11ea-94fd-42dd8d60d2a5.PNG">

slack에 올려주신대로 작성했는데 폴더가 생기지 않습니다

**Comment by encore-playdata** [comment]
안녕하세요! 폴더만 다운받는 방법 말고 해당 수강과정채널에서 최근에 지홍매니저님이 올려주신 sync 하는 방법이 기재되어 있습니다. 그방법대로 진행하시면 됩니다!

**Comment by Lee-Jong-Cheol** [comment]
네 감사합니다
