### ISSUE TITLE
지식플랫폼 질문테스트 3

### ISSUE THREAD

**Issue by sonsj1824** [encore-playdata/qna#104]
파이썬에서 True 혹은 False를 갖는 데이터 타입은 무엇인가?

**Comment by encore-playdata** [comment]
파이썬에서 True 혹은 False를 갖는 데이터 타입은 `bool`입니다.

**Comment by sonsj1824** [comment]
추가로 질문이 있으면 어떻게 해야돼?

**Comment by encore-playdata** [comment]
파이썬에서 True 혹은 False를 갖는 데이터 타입은 불리언(Boolean)입니다. 불리언 데이터 타입은 참과 거짓을 나타내는데, 참은 True로, 거짓은 False로 나타냅니다. 예를 들어, 1 > 2라는 조건문은 거짓이므로 False를 반환합니다.

**Comment by encore-playdata** [comment]
파이썬에서 True 혹은 False를 갖는 데이터 타입은 불(bool) 데이터 타입입니다. True와 False는 이 데이터 타입의 예약어로 사용되며, 이 데이터 타입은 조건문과 논리 연산에서 자주 사용됩니다. 예를 들어, if 문이나 while 문에서 조건을 검사할 때, 불 데이터 타입을 사용해야 합니다.
