### ISSUE TITLE
[박유현_2004_plt] 사전교육 퀴즈에 관련하여 질문이 있습니다.

### ISSUE THREAD

**Issue by yuhyeonp** [encore-playdata/qna#11]
https://docs.google.com/spreadsheets/d/1qV_Lh6L2qQXR6aIPryFsDt_KAzJDr7Gzt8qqWh7Qs1k/edit#gid=916642544

3월 18일에 파이썬 Quiz PART가 있는데요,
pre_python_01부터 20까지 중 절반을 하면 되는 것인가요?
몇번까지 정답을 제출하면 될까요?

**Comment by encore-playdata** [comment]
안녕하세요 박유현님, 
퀴즈 진행 일정 안내드립니다. 

```
1차 : quiz 1~20번
2차 : quiz 21~24번
3차 : 향후 업로드 예정
```
감사합니다!
