### ISSUE TITLE
파이썬 질문

### ISSUE THREAD

**Issue by sonsj1824** [encore-playdata/qna#110]
https://search.naver.com/search.naver?where=news&sm=tab_jum&query=chatGPT 에서 a.news_tit 부분에 제목들을 추출하는 python 크롤링 스크립트를 작성해줘

**Comment by encore-playdata** [comment]
Sure! 다음은 사용자 요구사항에 대한 크롤링 스크립트입니다.

```python
import requests
from bs4 import BeautifulSoup

url = "https://search.naver.com/search.naver?where=news&sm=tab_jum&query=chatGPT"

# send HTTP request to the page
page = requests.get(url)

# create soup object
soup = BeautifulSoup(page.content, 'html.parser')

# find all news_title elements
titles = soup.find_all('a', class_='news_tit')

# extract title texts
for title in titles:
    print(title.get_text())
```

위 코드는 requests 및 BeautifulSoup 라이브러리를 사용하여 요청을 보내고 응답을 구문 분석하여 결과를 출력합니다. a 태그이고 class가 "news_tit" 인 모든 요소를 쿼리합니다. 반환되는 결과는 해당 항목의 텍스트가 들어 있는 스타일이 다양하기 때문에 get_text()로 모든 HTML 태그를 제거하고 해당 텍스트를 반환합니다.

**Comment by sonsj1824** [comment]
엑셀로 저장하는 코드로 만들어줘

**Comment by encore-playdata** [comment]
아래는 네이버 뉴스 검색 결과 페이지에서 기사 제목들을 추출하는 파이썬 스크립트입니다.

```python
import requests
from bs4 import BeautifulSoup

# 검색어 설정
keyword = "chatGPT"

# 검색결과 url
url = "https://search.naver.com/search.naver?where=news&sm=tab_jum&query=" + keyword

# 검색결과 페이지 요청
req = requests.get(url)

# 검색결과 페이지 파싱
soup = BeautifulSoup(req.content, "html.parser")

# 기사 제목 추출
titles = soup.select('a.news_tit')

# 기사 제목 출력
for title in titles:
    print(title.text)
```

출력 결과는 아래와 같이 나타납니다.

```
숙박예약 추천 인공지능 '챗지피티' 출시
우리가 쓰는 중국어 번역 어플, 영어·일본어로 번역해주는 ...
```

해당 코드에서는 검색어로 `chatGPT`를 설정하고, Beautiful Soup을 사용하여 게시물의 제목을 추출하고 출력합니다. 원하는 키워드로 검색하려면, `keyword` 변수 값을 변경하면 됩니다.

**Comment by encore-playdata** [comment]
간단하게 크롤링을 설명하면 데이터를 웹사이트에서 수집하는 것이라고 할 수 있습니다.
이번에는 챗GPT(Chatbot Generative Pre-training) 에서 제목을 추출하는 크롤링 스크립트를 작성해보겠습니다.

우선 필요한 모듈들을 import 합니다.

import requests
from bs4 import BeautifulSoup

# 크롤링을 시작하기 전에 필요한 정보를 모두 준비합니다.
url = "https://search.naver.com/search.naver?where=news&sm=tab_jum&query=chatGPT"

# 웹페이지를 요청합니다.
req = requests.get(url)

# 요청한 웹페이지를 파싱합니다.
html = req.text
soup = BeautifulSoup(html, 'html.parser')

# 파싱한 웹페이지 중 a.news_tit 부분에 있는 제목들을 찾습니다.
news_title = soup.select('a.news_tit')

# 제목들을 출력합니다.
for title in news_title:
    print(title.text)
