### ISSUE TITLE
파이썬 지식플랫폼 질문 테스

### ISSUE THREAD

**Issue by sonsj1824** [encore-playdata/qna#111]
https://www.hrd.go.kr/hrdp/co/pcobo/PCOBO0100P.do?tracseId=AIG20210000328619&tracseTme=7&trainstCstmrId=500038398274&crseTracseSe=C0105&pageId=#kdcdToolTipContent

이 웹페이지에 <div class="accordionListArea">에  <dl class="item">들의 내용을 크롤링해서 엑셀로 저장하려고 한다.
1열에는  <span class="tit"> 훈련기간 </span>의 값을 추출해줘 예시는 2023-04-24 ~ 2023-06-02
2열에는 <th>모집 인원 (정원)</th>의 값을 추출해줘 예시는 200
3열에는 <th>수강확정인원/수강신청인원</th>의 값을 추출해줘 예시는 1명/&nbsp;	수강신청인원(선발 및 검토대기인원포함):&nbsp;3명

모든 <dl class="item">의 내용을 추출해서 엑셀로 저장하는 파이썬 코드를 작성해줘

**Comment by encore-playdata** [comment]
아래와 같이 코드를 작성할 수 있습니다. 

```Python
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://www.hrd.go.kr/hrdp/co/pcobo/PCOBO0100P.do?tracseId=AIG20210000328619&tracseTme=7&trainstCstmrId=500038398274&crseTracseSe=C0105&pageId=#kdcdToolTipContent'

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

data = []
items = soup.select('div.accordionListArea dl.item')
for item in items:
    period = item.select_one('span.tit').get_text(strip=True)
    recruit = item.select_one('th:contains("모집 인원 (정원)")').find_next_sibling('td').get_text(strip=True)
    confirm = item.select_one('th:contains("수강확정인원/수강신청인원")').find_next_sibling('td').get_text(strip=True)
    data.append([period, recruit, confirm])

df = pd.DataFrame(data=data, columns=['훈련기간', '모집 인원 (정원)', '수강확정인원/수강신청인원'])
df.to_excel('result.xlsx', index=False)
```

위 코드를 실행하면 같은 폴더에 `result.xlsx` 파일이 생성됩니다. 각 열의 값들은 DataFrame에 저장되어 있으므로, 필요에 따라 DataFrame을 활용하여 추가적인 가공이 가능합니다.
