### ISSUE TITLE
[박유현_2004_plt] 사전교육 quiz2_2.py 파일에 대해 질문이 있습니다.

### ISSUE THREAD

**Issue by yuhyeonp** [encore-playdata/qna#12]
열었을 때 다른 파일들과 달리 주석처리된 문제 부분은 없고
실행가능한 코드만이 있습니다.

어떤 문제에 대한 코드인지
문제부분 추가 부탁드립니다.

감사합니다!

**Comment by encore-playdata** [comment]
유현님 안녕하세요!
문제에 혼선을 드려서 죄송합니다.
quiz2_2 에 관한 문제입니다! 
'''
2.
년, 월, 일을 입력하면 그 날이 무슨 요일인지 출력하는 함수를 만드세요.
테스트코드
<입력>
print("%d년 %d월 %d일은 %s 입니다." % (myYear, myMonth, myDay, printDayOfTheWeek(myYear, myMonth, myDay)))
<출력>
연도를 입력하시오 : 2020
월을 입력하시오 : 3
일을 입력하시오 : 13
2020년 3월 13일은 금요일 입니다.
'''
