### ISSUE TITLE
[박하윤_2020_ai] git 에서 push가 안되는 문제

### ISSUE THREAD

**Issue by nagato10** [encore-playdata/qna#13]
![Cap 2020-03-26 12-56-04-286](https://user-images.githubusercontent.com/61655890/77608742-6f6ac300-6f61-11ea-902a-b8f3c17e505c.png)
안녕하세요. 알고리즘 퀴즈를 풀려고 push 를 하는데 계속 오류가 나서 질문 드립니다. 오류가 뜬 문항을 검색해서 자격 증명도 지워보고 git도 초기화 해보았지만 소용이 없었습니다. 어떻게 해결해야 할까요?

**Comment by encore-playdata** [comment]
자격증명 지우시고 다시 push 하셨을때 git 계정 다시 로그인 하는 창 뜨셨었나요?
계정 로그인 다시 해보시고 안되시면 명령어를 
git pull origin master 하신 후 다시 
git push origin master 해보시겠어요? 
그래도 안되시면 다시한번 질문 해주시면 감사하겠습니다.

**Comment by nagato10** [comment]
![Cap 2020-03-26 14-09-56-302](https://user-images.githubusercontent.com/61655890/77612446-81516380-6f6b-11ea-9777-f6194af692a0.png)
네 말씀하신대로 자격증명 지우고 댓글에 나와있는 것처럼 했는데 잘 안됩니다.

**Comment by ekmst1027** [comment]
제 생각에는 fork하신 계정의 프로젝트로 commit 후 push해야 하는데
encore-playdata계정의 프로젝트로 push하니까 생기는 문제같습니다.
```
git remote get-url origin --all
```
위 명령어로 remote 주소도 확인해보세요.
"https://github.com/encore-playdata/"로 시작하는 주소라면 remote의 대상이 잘못된겁니다.
본인의 아이디가 포함된 fork하신 계정을 clone한 다음에 commit 후 push하면 될것입니다.

**Comment by encore-playdata** [comment]
클론 할때도 제대로된 주소를 입력했는데도 똑같은 현상이 일어나서 
fork와 해당 repo 그리고 git bash 까지 삭제후 다시 처음부터 진행을 하니 되었습니다.
