### ISSUE TITLE
[김형욱_2004 anl] algorithm quiz 4번에 질문 있습니다.

### ISSUE THREAD

**Issue by HyeongWookKim** [encore-playdata/qna#14]
우선 제가 입력한 코드는 다음과 같습니다.

![1](https://user-images.githubusercontent.com/34057417/79122384-76535b80-7dd2-11ea-86a8-a2ad988299ae.JPG)

이렇게 입력을 하면, 출력 결과가 다음과 같이 끝에 ",(콤마)"가 지워지지 않고 출력됩니다..

![2](https://user-images.githubusercontent.com/34057417/79122536-dd711000-7dd2-11ea-9686-f66febd120c1.JPG)

제 코드가 문제에 적합하지 않게 작성된 것일 수도 있다는 생각에 질문드립니다.

제가 문제를 정확히 푼게 맞나요?

**Comment by encore-playdata** [comment]
뒤에 콤마가 생기셔도 상관없습니다.
혹시나 뒤에 콤마를 없애고 싶으시면 join 이라는 리스트 메서드를 이용하시면 됩니다. 
형욱님이 작성하신 코드에 몇가지 추가하여 올려드립니다. 확인해보시고 궁금하신점 있으시면 다시한번 질문 남겨주시면 됩니다.!
def greedy():
    value = int(input('액스임력 : '))
    coin_list = list(map(int, input('동전의 종류 :').split(" ")))
    b=[]

    count = 0
    coin_list.sort(reverse=True)

    for i in coin_list:
        count += (value // i)
        b.append('{}원 동전 {}개'.format(i, value // i))
        value -= (value // i) * i
    x=','
    answer=x.join(b)
    return print((answer))

greedy()
