### ISSUE TITLE
[2020-05-09]만나서 반갑습니다,

### ISSUE THREAD

**Issue by Hyunmin1992** [encore-playdata/qna#16]
안녕하세요 모두 알고리즘의 달인이 될 수 있도록 열심히 노력합시다.

**Comment by yuhyeonp** [comment]
서초 플랫폼반 박유현입니다^^ 좋은 강의 감사드립니다!

**Comment by HyeongWookKim** [comment]
안녕하세요~

데이터 분석 과정반 김형욱입니다 :)

오늘 특강 감사했습니다! 👏👏

**Comment by Blood-Red** [comment]
안녕하세요. 반갑습니다. 
남부 분석반 오정원이라고 합니다.

**Comment by Parkhwanju** [comment]
안녕하세요ㅎㅎ 서초 플랫폼반 박환주입니다!! ◡̈

**Comment by swim1927** [comment]
남부 플랫폼반 김수영입니다^^ 오늘 특강 감사합니다!

**Comment by Blackraven93** [comment]
유익한 강의 감사합니다.

**Comment by Naeya7** [comment]
안녕하세요~ 서초 플랫폼반 김시내입니다. 알고리즘 열심히 해보겠습니다!

**Comment by DoJinCH** [comment]
안녕하세요 분석반 채도진입니다
오늘 특강 감사합니다^^

**Comment by Kwonseoyoung-2020** [comment]
안녕하세요! 분석반 권서영입니다. 오늘 고생하셨습니다!

**Comment by moon-juri** [comment]
안녕하세요. 데이터분석반 문주리입니다. 반갑습니다 :) 남은 기간동안 잘 부탁드려요~~~

**Comment by Lee-Jong-Cheol** [comment]
안녕하세요 남부 플랫폼반 이종철입니다.  오늘 고생하셨습니다.

**Comment by kan99276** [comment]
안녕하세요. 데이터분석반 박정수입니다. 잘부탁드려요!

**Comment by seungyeon0917** [comment]
안녕하세요. 서초 플랫폼반 최승연입니다!
