### ISSUE TITLE
저.. 혹시 github page를 만들고 싶은데..

### ISSUE THREAD

**Issue by JinSeonGyeong** [encore-playdata/qna#68]
hexo로 만들고 있는데 구글에서 찾은 곳에서 알려주는게 좀.. 불친절한거 같아서..
디테일 하게 물어보고 싶은데 .. 알려주실 수 있나요?
혼자 삽질해 봐야하나..ㅠㅠ

**Comment by Hyunmin1992** [comment]
관계자 분들 중에 hexo를 활용한 페이지를 제작해보셨거나 알고 계신분이 있는지 알아보도록 하겠습니다. 계시다면 도움 드릴 수 있도록 요청하도록 하겠습니다.

**Comment by Hyunmin1992** [comment]
답변이 늦은 점 죄송합니다. 도움을 드리고자 관계자 중 Node JS를 다루실 수 있는 분이 있는지 알아본 결과 한 분 계셨는데 그 분 역시 hexo는 사용해본적이 없다고 하셔서 hexo에 대한 큰 도움을 드리지 못하는 점 정말 죄송합니다.
