### ISSUE TITLE
quiz2_2번 문제 입력, 출력이 이해되지 않습니다.

### ISSUE THREAD

**Issue by ekmst1027** [encore-playdata/qna#7]
```
년, 월, 일을 입력하면 그 날이 무슨 요일인지 출력하는 함수를 만드세요.

테스트코드
<입력>
print("%d년 %d월 %d일은 %s 입니다." % (myYear, myMonth, myDay, printDayOfTheWeek(myYear, myMonth, myDay)))

<출력>
연도를 입력하시오 : 2020
월을 입력하시오 : 3
일을 입력하시오 : 13
2020년 3월 13일은 금요일 입니다.

```
위 문제에서 입력 출력부분이 좀 혼란스러운데요,
연도, 월, 일을 입력하면 "2020년 3월 13일은 금요일 입니다."라는 문장이 나와야 하는건지
아니면 print문의 코드를 입력하면 정말로 출력부분처럼 나와야 하는건지 의도를 잘 모르겠습니다.

**Comment by encore-playdata** [comment]
년,월,일을 입력하면 요일이 나오는 함수(printDayOfTheWeek)를 만드시고 난뒤 input 값으로 myYear, myMonth, my,Day를 입력받으면  print 값으로 출력되게 하시면 됩니다.
