### ISSUE TITLE
Programmers 정수 내림차순으로 배치하기

### ISSUE THREAD

**Issue by geondongkim** [encore-playdata/qna#70]
아래 4가지 메소드 모두 이클립스에서는 에러가 나지 않지만 
프로그래머스 홈페이지에서는 런타임에러가 뜹니다. 어떤 부분이 잘못되었는지 궁금합니다.
public static long solution(long n) {
		 long answer = 0;
		 String str = String.valueOf(n);
		 String[] strArr = str.split("");
		 Arrays.sort(strArr, Collections.reverseOrder());
		 String res = "";
		 for (int i = 0; i < strArr.length; i++) {
			res += strArr[i];
		 }
		 answer = Long.parseLong(res);
		 return answer;
	    }
	 public static long solution2(long n) {
		 long answer = 0;
		 String str = Long.toString(n);
		 String[] strArr = new String[str.length()];
		 strArr = str.split("");
		 Arrays.sort(strArr, Collections.reverseOrder());
		 String res = "";
		 for (int i = 0; i < strArr.length; i++) {
			 res += strArr[i];
		 }
		 answer = Long.parseLong(res);
		 return answer;
	 }
	 public static long solution3(long n) {
		 long answer = 0;
		 int len = Long.toString(n).split("").length;
		 
		 String[] strArr = new String[len];
		 strArr = Long.toString(n).split("");
		 
		 String res = "";
		 Arrays.sort(strArr, Collections.reverseOrder());
		 
		 for (int i = 0; i < len; i++) {
			 res += (long) Integer.parseInt(strArr[i]);
		 }
		 answer = Long.parseLong(res);
		 return answer;
	 }		 
	public static long solution4(long n) {
		long answer = 0;
		ArrayList<Long> arr = new ArrayList<>();
		
		while (n > 0) {
			arr.add(n % 10);
			n /= 10;
		}
		Collections.sort(arr);
		long temp;
		for (int i = 0; i < arr.size(); i++) {
			temp = arr.get(i);
			for (int j = 0; j < i; j++) {
				temp *= 10;
			}
			answer += temp;
		}
		return answer;
	}

**Comment by Hyunmin1992** [comment]
![image](https://user-images.githubusercontent.com/51353590/81772036-b156c500-951f-11ea-94f8-623bfa049dfb.png)
보내주신 첫 번째 코드로 프로그래머스 확인결과 정답으로 통과하고 있습니다.

**Comment by Hyunmin1992** [comment]
추가적으로 프로그래머스는 테스트할경우 작성된 함수 solution을 호출하여 결과를 확인합니다.
만약 메소드명을 바꾸셨다면 런타임 에러가 발생합니다.

**Comment by geondongkim** [comment]
답변 감사합니다. 프로그래머스는 import가 필요 없는 줄 알았습니다...
