### ISSUE TITLE
발표에 관한 질문입니다.

### ISSUE THREAD

**Issue by YoungkeunAhn** [encore-playdata/qna#71]
1. 코로나 19 문제 때문에 오후 9시에 유튜브 라이브로 발표를 진행한다고 하셨는데 9시에 시간이 되는 사람이 있어서 저희 반 따로 자체적으로 먼저 발표를 진행해도 되나요?

2. 혹시 유튜브 라이브를 진행하지 못할 경우 반에서 발표 할 수 있을 때만 발표를 진행해도 되나요?

**Comment by Hyunmin1992** [comment]
관계자분들과 상의하에 빠른답변 드릴 수 있도록하겠습니다
