### ISSUE TITLE
'행렬의 덧셈' 질문 드립니다.

### ISSUE THREAD

**Issue by epiphany-r** [encore-playdata/qna#73]
프로그래머스 '행렬의 덧셈' 문제를 풀던 중 질문사항이 있어서 이슈 올립니다!

def solution(arr1, arr2):
    answer = []
    answer1 = []

    for i in range(len(arr1)):
        for k in range(len(arr1[i])):
            ans1 = arr1[i][k]+arr2[i][k]
            answer.append(ans1)
        answer1.append(answer)
    return answer1

위와 같이 풀었을 때, 
입력값이 [[1, 2], [2, 3]], [[3, 4], [5, 6]]일 경우 
결과가 [[4, 6, 7, 9], [4, 6, 7, 9]] 이렇게 나오고,
for문 안에서 answer 리스트를 초기화하는 코드를 넣으면 정답이 나오는데요.

위와 같이 풀면 왜 리스트가 두번 반복되는지 궁금합니다.
작동 순서를 제가 잘못 알고 있어서 헷갈리는 걸까요??

**Comment by Hyunmin1992** [comment]
안녕하세요.

질문에 대한 답을 드리기 전에 이해를 돕기 위해 하나 먼저 설명드리겠습니다.

a = 3
b = a
a = 4
print(b)

위의 코드를 활용하실 경우 b는 3이라는 결과를 얻을 수 있습니다.
그 이유는 b = a 의 작업이 b 는 a 를 참조하는 것이 아닌 a의 값을 저장하였기 때문입니다.
하지만 배열의 경우에는 조금 다릅니다.

c = [1,2,3]
d = c
c[1] = 5 
print(d)

위의 코드의 경우 d는 c의 값 전체를 가져온 것이 아닌 c의 주소값을 참조하고 있습니다.
그렇기 때문에 c를 수정할 경우 d도 변화하는 것을 볼 수 있습니다.
그러나

c = [1,2,3]
d = c
c = [ ]
print(d)

이 경우에는 d는 c의 특정한 주소값을 가르키고 있으며 c가 수정이 아닌 새롭게 초기화가 될 때,
c와 c의 주소값의 연결이 끊길뿐 d는 여전히 c를 가르키고 있기에 d는 여전히 [1,2,3]을 나타내는 주소값을 가지고 있습니다.

그럼 질문에 대한 답을 드리자면

answer1.append(answer)

위 작업은 answer1 에 answer의 주소값을 입력하는 것 입니다.
따라서 answer가 새롭게 초기화가 되지 않고 수정이 되는 경우 먼저 들어간 answer 성분에도 변화가 생기는 것입니다.

결국 answer1의 첫번째 성분 두번째 성분 모두 같은 answer를 가르키게 되는 것입니다. 

여기서 얕은 복사와 깊은 복사에 대해 알아두시길 권장드립니다.
얕은 복사는 주소값을 참조해 배열을 만드는 것이며(일반적인 방법)
깊은 복사는 같은 성분들을 가지지만 다른 주소값을 갖는 새로운 배열을 생성하는 것입니다.
깊은 복사의 경우 효율성측면에서 상당한 시간을 잡아 먹으므로 특별한 경우가 아닌 이상은 피하는 것이 일반적입니다.

아래는 깊은 복사의 방법입니다.

import copy

새로운배열 = copy.deepcopy(복사될배열)

답변이 충분한 도움이 되었길 바라며 궁금한점은 언제든지 질문해주시길 바랍니다.ㅎㅎ

**Comment by epiphany-r** [comment]
answer1에 answer 값을 넣으면 answer 값이 초기화되는 개념으로 제가 잘못 알고 있었던 것 같네요!!
answer1에 넣더라도 answer에는 전에 들어간 값이 존재하는 상태로 다시 for문을 작동하기때문에 answer1에 중복된 값을 또 넣게 되는 거군요. 답변 감사합니다 ^^!!
