### ISSUE TITLE
[유연승_2004-데이터분석]  알고리즘스터디2단계 13주차 LV3.등교길 질문입니다.

### ISSUE THREAD

**Issue by souckkr** [encore-playdata/qna#74]
처음에는 외곽지역(?)과 웅덩이를 None으로 설정하여 문제를 풀었지만 통과하지 못하였고 두번째는 0으로 설정하여 통과하였습니다.

그런데 테스트케이스들을 여러개 구현하여 첫번째 코드에 넣었을때 전부다 통과를 했는데 프로그래머스 상에서는 실패하였습니다. 외곽지역과 웅덩이를 0으로 설정했을때랑 방식은 똑같은데 왜 첫번째 코드가 왜 실패했는지 알고싶습니다.

### def solution(m, n, puddles):
    answer = 0
    #외곽지역을 None로 설정
    memo=[[0 if i !=0 else None for i in range(m+1)] for j in range(n+1)] 
    for i in range(len(memo[0])): 
        memo[0][i] = None
    memo[1][1] = 1 #집       
    for i in puddles: #웅덩이 None로 설정'
        memo[i[0]][i[1]] = None
    # 윗칸과 왼쪽칸까지의 최적 경로의 수 합이 현재칸까지의 최적 경로의 수   
    for k in range(1,n+1):
        for j in range(1,m+1):
            if memo[k][j] is None: #웅덩이를 만났을때    
                continue
            if memo[k][j-1] is None and memo[k-1][j] is None: #윗쪽과 왼쪽이 None라면 현재칸도 None
                memo[k][j] is None
            elif memo[k-1][j] is None: #위쪽칸이 None일때 왼쪽칸이 현재칸의 경로의 수
                memo[k][j] =memo[k][j-1]
            elif memo[k][j-1] is None: #왼쪽칸이 None일때 위쪽칸이 현재칸의 경로의 수
                memo[k][j] =memo[k-1][j]
            else:
                memo[k][j] = memo[k-1][j] + memo[k][j-1] # 현재칸의 경로 = 윗칸과 왼쪽칸까지의 최적 경로의 수 합
    return memo[-1][-1] % 1000000007

### def solution(m, n, puddles):
    answer = 0
    memo=[[0 for i in range(m+1)] for j in range(n+1)] 
    memo[1][1] = 1 #집       
    for k in range(1,n+1):
        for j in range(1,m+1):
            if [j,k] in puddles:
                continue
            if k==1 and j==1:
                continue
            memo[k][j] = memo[k-1][j] + memo[k][j-1]
    return memo[-1][-1] % 1000000007

**Comment by rjh211** [comment]
웅덩이 설정하실때 행과열이 반대네요

**Comment by souckkr** [comment]
아!... 그러네요 ㅋㅋㅋ 통과했습니다.. ㅠㅠ 감사합니다!.
