### ISSUE TITLE
소수 찾기 문제 질문드립니다.

### ISSUE THREAD

**Issue by RokcSSGChae** [encore-playdata/qna#76]
안녕하세요 소수찾기 문제 질문드립니다.
다름이 아니라 solution 메소드를 다음과 같이 구성해서 return 값은 정확히 나옵니다.
하지만 효율성 테스트를 통과하지 못하는데 그 이유가 궁금합니다.
```
class Solution {
    public int solution(int n) {
		int ret = 0;
		for (int i = 2; i <= n; i++) {
			for (int j = 2; j <= i; j++) {
				if (j == i) {
					ret++;
				} else if (i % j == 0) {
					break;
				}
			}
		}
		return ret;
	}
}
```
추가로 제가 현재 java로 알고리즘 테스트 진행하고 있는데 코딩 테스트 준비하는데 있어서 어떤 언어로 준비하는 것이 좋은지 궁금합니다.

**Comment by Hyunmin1992** [comment]
안녕하세요 @RokcSSGChae님

2가지 질문은 주셨는데요.
1. 효율성 테스트 해결방법
2. 어떤 언어로 준비하는 것이 좋은가

**Comment by Hyunmin1992** [comment]
우선 소수는 1과 자신을 제외한 약수가 없는 수입니다.
전체를 탐색하는 방법도 있지만 약수는 숫자의 제곱근을 기준으로 작은 수와 큰 수를 곱하기 때문에 계산량을 줄일 수 있습니다.
ex) 16 = 1, 2, 4(16의 제곱근), 8, 16  

그렇기 때문에 제곱근까지만 나눠 보면 소수인지 여부를 확인 할 수 있습니다.

``` java
class Solution {
    public int solution(int n) {
		int ret = 0;
		for (int i = 2; i <= n; i++) {
			int sqrt = (int)Math.sqrt(i) + 1;
			for (int j = 2; j <= sqrt; j++) {
				if (j == sqrt) {
					ret++;
				}
				else if (i % j == 0) {
					break;
				}
			}
		}
		return ret;
	}
}
```

**Comment by Hyunmin1992** [comment]
코딩 테스트로 어떤 언어로 준비하는 것이 좋은가는 정답이 없어 기준을 가지고 선택하시면 됩니다.

### 가장 잘하는 언어, 빠르게 구현할 수 있는 언어
알고리즘 테스트는 제한된 시간 내에서 코드를 완성해야 합니다.
문제를 해석하고 알고리즘을 만들어 자신이 풀 수 있어도 구현하는 시간이 오래 걸리면 말짱 도루묵입니다.
해당 언어의 라이브러리를 잘 알고 있다면 더 빠르게 구현이 가능합니다.

### 목표하는 분야 혹은 회사에서 주로 사용하는 언어
알고리즘 테스트를 하는 이유는 다양하지만 취업하려는 회사는 C++ 인데 java로 한다면 취업을 성공하더라도 다시 배워야 한다는 단점이 있습니다.
그래서인지 면접에서도 회사가 사용하는 주 언어를 기준으로 물어보기도 합니다. 주 언어가 같다면 공부를 더 효율적으로 할 수 있습니다.

### 아무것도 없는 채로 처음부터 한다면?
다수가 사용하는 언어를 추천합니다. (C++, Java, Python 등)

**Comment by RokcSSGChae** [comment]
답변 감사드립니다!
