### ISSUE TITLE
[강셰인_202006_yeong_iitp] 코딩테스트 연습 문제 중 2016 질문 있습니다.

### ISSUE THREAD

**Issue by shanekang** [encore-playdata/qna#78]
안녕하세요,

2016년 요일을 구하는 문제에서
저는 날짜 관련 함수가 있는 datetime 모듈을 쓰지 않고 한번 코드를 짜 보았고,
이번에는 오타가 없는 지 잘 확인 해보고 또 제가 여러 날짜를 넣어서 실험을 해보았을 때 
잘 동작을 하지만 코드 채점을 해보면 아래와 같이 몇몇 테스트를 패스하지 못하고 있어요.
 
![image](https://user-images.githubusercontent.com/53311001/87849209-b8d08b00-c921-11ea-9979-3474e2db2e08.png)

어느 부분을 놓치고 있는 지 잘 모르겠고 알고싶어서 질문드립니다!
감사합니다! :-)
```
def solution(a, b):
    month_days = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    days = ["MON","TUE","WED","THU","FRI","SAT","SUN"]
    total_days = 0
    for i in range(0, a):
        total_days += month_days[i]
    day_index = (total_days + b) % 7
    
    return days[day_index]
```

Best regards,
Shane Kang

**Comment by qus0in** [comment]
상단의 코드가 테스트 케이스를 틀리는 까닭은 아래 두 가지 입니다.
1) 1월의 경우엔 더해질 이전 달의 날짜가 없는데 더하고 시작됨
2) 2016년 1월 1일이 금요일이라는 것이 반영되어 있지 않음

현재 기본적으로 제시되어 있는 5월 24일, 1월 7일의 케이스에는 기존에 제시한 로직만으로 적합합니다만,
2월 1일, (월요일) 케이스를 넣어보시면 틀리게 나오는 걸 볼 수 있습니다.

아래는 수정한 코드입니다.
```
def solution(a, b):
    month_days = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    # (수정사항1) 1월 1일이 금요일, 다시 말해 이전 달에 추가 되는 값이 없을 때 인덱스 1의 값이 금요일이므로, 0은 목요일부터 시작해서 days를 나열
    days = ["THU", "FRI","SAT","SUN", "MON","TUE","WED"]
    total_days = 0
    # (수정사항2) 1월일 경우엔 for문 자체를 돌릴 필요가 없으므로 a-1을 통해서 range(0, 0) = 빈 리스트를 만들어주면서 값이 더해지지 않게 함
    for i in range(0, a - 1):
        total_days += month_days[i]
    day_index = (total_days + b) % 7
    
    return days[day_index]
```

**Comment by shanekang** [comment]
아 정말 그렇네요... ㅠ ㅎㅎ
답변해주신 내용 정말 감사합니다! 진짜 도움이 많이 되는 것 같아요! 👍
