### ISSUE TITLE
quiz2_3번 입력, 출력이 잘 안맞는것 같습니다.

### ISSUE THREAD

**Issue by ekmst1027** [encore-playdata/qna#8]
'''
3.
Card 클래스를 생성해 카드에 충전기능, 소비기능, 잔액을 알려주는 기능을 넣으시오.
-충전기능 (charge)
-소비기능 (consume)
print 기능(print) # 잔액이 ( ) 원 입니다.

테스트코드
<입력>
card = Card()
card.charge(20000)
card.consume(3000,'마트')
card.consume(10000,'영화관')
card.consume(13000,'마트')
card.print()

<출력>
잔액이 20000원 입니다.
마트에서 3000원 사용했습니다.
영화관에서 8000.0원 사용했습니다.
잔액이 부족합니다
잔액이 9000.0원 입니다.
'''

위 문제에서 중간에 'card.consume(10000,'영화관')' 인데
'영화관에서 8000.0원 사용했습니다.' 라고 출력되는것 같습니다.
출력부분대로 하면
```
card.charge(20000)
card.consume(3000,'마트')
card.consume(10000,'영화관')
```
라고 하거나 출력부분을 바꿔야할것 같습니다.

그리고 출력부분에서 값이 
마트출력부분은 정수형인데
그 아래부터 소수형으로 바뀌어서 출력이 되는것 같습니다.
한가지 type으로 통일되는게 좋을것 같습니다.

**Comment by encore-playdata** [comment]
'''
3.
Card 클래스를 생성해 카드에 충전기능, 소비기능, 잔액을 알려주는 기능을 넣으시오.
-충전기능 (charge)
-소비기능 (consume)
-영화관에서 카드를 사용하면 20% 할인율 적용
print 기능(print) # 잔액이 ( ) 원 입니다.

테스트코드
<입력>
card = Card()
card.charge(20000)
card.consume(3000,'마트')
card.consume(10000,'영화관')
card.consume(13000,'마트')
card.print()

<출력>
잔액이 20000원 입니다.
마트에서 3000원 사용했습니다.
영화관에서 8000원 사용했습니다.
잔액이 부족합니다
잔액이 9000원 입니다.
'''
