### ISSUE TITLE
[유연승_202004_남부_데이터분석] 알고리즘 3단계 N-Queen 질문

### ISSUE THREAD

**Issue by souckkr** [encore-playdata/qna#80]
`
def check(i, col):
    global answer
    n = len(col)
    if (promising(i, col)):
        if i == (n-1):
            answer += 1
            print(col)
        else:
            for j in range(n):
                col[i] = j
                check(i+1, col)
                
def promising(i, col):
    for k in range(i):
        
        if (col[i] == col[k]) or (abs(col[i]-col[k]) == i-k):
            return False
    return True

def solution(n):
    global answer
    answer = 0
    
    col = [0]*n
    check(0,col)
    return answer
`

여기저기 찾아보면서 체크해봤는데 아무래도 틀린것이 없는데 코드가 작동을 하지 않습니다.
어떤 부분이 문제인가요.. ㅠㅠ

**Comment by Hyunmin1992** [comment]
안녕하세요. N-Queen은 어려운 문제인데 열심히 도전하시는 모습 멋있습니다.

우선 문제를 어떤 방법으로 접근하셨는지는 잘 모르겠으나,
주어진 코드로 보아 col이라는 행렬은 각 퀸이 몇 층에 놓여있느지를 나타내는 것 같습니다.

예를들어 col 값이 [ 2 , 0 , 3 , 1 ] 인 경우에는

위에서 첫 번째 층에는 값 0 을 찾아 두 번째 위치,         0  1  0  0
위에서 두 번째 층에는 값 1 을 찾아 네 번째 위치,         0  0  0  1
위에서 세 번째 층에는 값 2 을 찾아 첫 번째 위치,         1  0  0  0
위에서 네 번째 층에는 값 3 을 찾아 세 번째 위치,         0  0  1  0

위와 같은 방법으로 접근한 것으로 보여집니다.

우선 제가 보았을 때 두 가지 문제점이 있습니다.

첫 번째는 문제는 많은 분들이 알고리즘을 처음 시작할때 겪는 문제입니다.

바로 배열의 복사 문제입니다.

check 함수 바로 아래

for j in range(n):
    col[i] = j
    check( i + 1 , col )

에서 check가 계속하여 재귀호출이됩니다.

여기서 문제는 j = 0 일때의 col 과 j = 1일 때의 col이 같다고 생각하여 발생하는 문제로 여겨집니다.

반복문 안에서 j = 0 일때의 col을 사용하여 재귀 호출을 통해 층 검사를 할 것입니다.

 j = 0일 때의 모든 재귀함 수가 끝나고 반복문의 j = 1일 때의 재귀함수가 다시 시작될 것입니다.

그러나 j = 0 의 check에서 col이 이미 바뀌어버렸기 때문에 j = 1에서의 층 검사가 원활하게 돌아가지 않습니다.

이런 경우, 흔히 반복문 안의 코드를 다음과 같이 쳐서 col을 기존의 배열로 다시 되돌리는 방법을 많이 활용합니다.

       temp = col[i]
       col[i] = j
       check(i+1, col)
       col[i] = temp

이 부분은 배열의 얕은 복사와 깊은 복사에 대한 차이에 대한 이해가 필요합니다.

이 부분에 대하여 답변한 적이 있으니 아래 링크 참고해주시면 감사하겠습니다.
https://github.com/encore-playdata/qna/issues/73

그리고 또 다른 문제로 보여지는 것이 col 의 시작값이 [ 0 , 0 , 0 , 0 ] 인 것입니다.
[ 0 , 0 , 0 , 0 ]은 첫 번째 층에 4개의 말이 모두 놓여 있는 의미로 코드가 해석하게되어
두 번째 층은 어떠한 말도 위치할 수 없는 문제가 발생하기 때문입니다.

문제를 접근하셨던 방법이 코드를 통해 제가 추측한 방법이 아니라면 저의 답변은 잘못되었을 수도 있습니다.
만약 제가 추측한 접근방법이 맞다면 위 문제를 해결하는 코드를 구사한다면 조금 더 정답에 가까운 코드를 구사할 수 있을 것입니다.
만약 제가 추측한 접근방법이 아니라면 어떤 방법으로 접근 하였는지 알려주신다면 그에 맞게 다시 답변을 준비하도록 하겠습니다.

감사합니다.

**Comment by souckkr** [comment]
친절한 답변 감사드립니다.
답변을 참고하여 문제를 해결하였습니다.
문제는 col 의 시작값이 [ 0 , 0 , 0 , 0 ] 으로 시작하여 promising이 False로 시작하는 거였습니다.
따라서 앞에 0을 하나 추가하여(  [ 0 , 0 , 0 , 0, 0 ]) 1열 2열이 처음부터 비교되지 않게 조치를 하였습니다.
다만 추가로 질문이 있습니다.

`
   temp = col[i]
   col[i] = j
   check(i+1, col)
   col[i] = temp
`

이부분을 수정을 하였는데 수정을 해도 배열이 기존배열로 돌아가지 않는 것을 확인하였습니다.
왜 저 배열이 기존배열로 돌아가지 않는지 알고 싶습니다. ㅠㅠ
(사실 저는 앞열부터 1씩 더해가며 비교해야 하기 때문에 배열 초기화 할 필요가 없다고 생각합니다)


수정한코드
`
def check(i, col):
    global answer
    n = len(col)-1
    if (promising(i, col)):
        if i == n:
            answer += 1
        else:
            for j in range(1,n+1):
#                 temp = col[i]
                col[i+1] = j
                check(i+1, col)
#                 col[i] = temp
                print(col)
                
def promising(i, col):
    for k in range(1,i):
        if (col[i] == col[k]) or (abs(col[i]-col[k]) == i-k):
            return False
    return True

def solution(n):
    global answer
    answer = 0
    
    col = [0]*(n+1)
    check(0,col)
    return answer
`

**Comment by Hyunmin1992** [comment]
답변이 조금 늦은 점 죄송합니다.

우선 어제 드린 답변에 대하여 이해하시고  문제를 풀었다니 다행입니다.

배열이 기존배열로 돌아가지 않는다고 말씀 주셨는데

첫 번째로는 print(col)의 위치입니다.

조건문 안에 있기때문에 아무래도 검사하는 col이 아닌 promising한 col에 대해서만 출력하고 있어서

여러개의 col들 중에 일부분만 출력이 되는 것입니다.

두 번재로는  반복문 안의 아래 코드 부분입니다.

                 temp = col[i]
                col[i+1] = j
                check(i+1, col)
                 col[i] = temp

col의 i번째를 temp에 담아두고 col [ i+1 ]을 변경하였다는 것 입니다.

위 두가지 사항을 수정하여

n=4 일 때 solution(4)를 출력해본다면

[0, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 1, 1, 0, 0]
[0, 1, 2, 0, 0]
[0, 1, 3, 0, 0]
[0, 1, 3, 1, 0]
[0, 1, 3, 2, 0]
[0, 1, 3, 3, 0]
[0, 1, 3, 4, 0]
[0, 1, 4, 0, 0]
[0, 1, 4, 1, 0]
[0, 1, 4, 2, 0]
[0, 1, 4, 2, 1]
[0, 1, 4, 2, 2]
[0, 1, 4, 2, 3]
[0, 1, 4, 2, 4]
[0, 1, 4, 3, 0]
[0, 1, 4, 4, 0]
[0, 2, 0, 0, 0]
[0, 2, 1, 0, 0]
.....

다음과 같이  [0 , 1 , 0 , 0 , 0 ] 에서 시작하여서

정상적으로 초기화되어

[ 0 , 2 , 0 , 0 ,0 ] 이 다시 시작되는 것을 확인하실 수 있을 것 입니다.

답변에 부족한 부분이 있다면 다시 궁금하신 점을 질문 주신다면 조금 더 이해가 될 수 있도록 준비해보도록 하겠습니다.

감사합니다.
