### ISSUE TITLE
[김푸름_2101_ai_n3] 네트워크 문제에 질문 있습니다.

### ISSUE THREAD

**Issue by Green0v0** [encore-playdata/qna#81]
네트워크 문제를 bfs로 풀어보려고 했습니다. 그런데 테스트 케이스 1,2,4,7번에서 통과가 안됩니다 ㅠㅠ
```
from collections import deque

def bfs(n, computers, visited):
    queue = deque([0])
    while queue:
        i = queue.popleft()
        visited[i] = True

        for x in range(n):
            if x == i:
                continue

            if visited[x] == True:
                continue

            # if computers[i][x] == 1:
            if computers[i][x] == 1 or computers[x][i] == 1:
                queue.append(x)

    return 1

def solution(n, computers):
    visited = [False] * n
    answer = 0

    for i in range(n):
        if not visited[i]:
            answer += bfs(n, computers, visited)

    return answer
```

![image](https://user-images.githubusercontent.com/51433857/108825388-4be34900-7606-11eb-9cdd-ed91a0f00352.png)

다른 분들의 질문하기도 참고해봤더니 주어진 데이터가 대칭이 아닐 수도 있다고 해서 조건을 ` if computers[i][x] == 1 or computers[x][i]== 1 ` 로 바꿨는 데도, 통과되지 않았습니다. 
제가 생각하지 못하고 빼먹은 다른 조건이 있는지 궁금합니다. 또한 DFS/BFS 공부가 처음이라 이렇게 구현하는 것이 맞는지, 참고할 자료는 없는지 여쭙고 싶습니다.😀

**Comment by Hyunmin1992** [comment]
안녕하세요
해당 코드들은 큐를 활용하여 bfs 구현을 잘해주셨습니다.

위 코드를 훑어보고 한 가지 오류를 발견하였습니다.
 
그러나 정말 작은변화만 줄수 있다면 정답에 도달할 수 있어 정답을 드리기보다 정말 작은 힌트와 반례를 드리도록 하겠습니다.

힌트) bfs함수가 시작될때마다 deque([0]) 를 어떠한 경우에도 시작값으로 사용하고 계시는데 왜 0번째섬을 항상 시작값으로 사용하시는지 알 수 있을까요?

반례 ) 

A. solution(4,[[1,0,0,1],[0,1,1,0],[0,1,1,0],[1,0,0,1]]) 기대답안 : 2 , 제출답안 : 3

B. solution(5,[[1,0,0,1,0],[0,1,1,0,0],[0,1,1,0,0],[1,0,0,1,0],[0,0,0,0,1]]) 기대답안 : 3 , 제출답안 : 4

위 힌트를 토대로 오류 잡으실 수 있으시면 좋겠습니다.

그래도 답안 도출이 어려우시다면 답변 다시 작성해주시길 바랍니다.
어디를 수정해야할지 알려드리도록 하겠습니다.

감사합니다.

**Comment by Hyunmin1992** [comment]
추가적으로 BFS는 큐를, DFS는 스택을 활용합니다.

**Comment by Green0v0** [comment]
앗 그렇군요 해결했습니다! 힌트 감사합니다🥰
