### ISSUE TITLE
[신주용_2108_인공지능13기]1주차 2번째문제 질문입니다.

### ISSUE THREAD

**Issue by SJY0917032** [encore-playdata/qna#83]
![carbon (1)](https://user-images.githubusercontent.com/88534701/128733381-364b4499-dd15-495e-a307-b859b8352189.png)

사진과같이 코드를 짰는데

마지막 테스트케이스에서 통과를 못하네요 혹시 어디부분이 문제일까요?..

**Comment by encore-playdata** [comment]
첫번째 while문 수식이 잘못된거로 확인 됩니다. 
문제를 확인해보면 7일째 되는 날에 배포가 가능한 경우인데, 위에 적혀있는 수식은 100이 포함이 되어, 카운팅이 한번 더 되어 값이 달라지는것 같습니다.
수식을 while(progresses[i] < 100) 로 변경하여 푸시면 해결되실거로 확인됩니다!

**Comment by SJY0917032** [comment]
해결됐습니다!
